#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jul 26, 2020 02:51:04 AM BST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #262626 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 299x49+913+211
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Add Window"
    vTcl:DefineAlias "$top" "AddWindow" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground #262626 -activeforeground black -background #262626 \
        -font {-family {DejaVu Sans} -size 13} -foreground #dddddd \
        -highlightcolor black -justify left -text Title: 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "AddWindow" 1
    entry $top.ent44 \
        -background #141414 -font TkFixedFont -foreground #dddddd \
        -highlightbackground #141414 -highlightcolor black \
        -highlightthickness 0 -insertbackground black -relief flat \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "titleEntry" vTcl:WidgetProc "AddWindow" 1
    button $top.but45 \
        -activebackground #004c0a -activeforeground black -background #141414 \
        -borderwidth 0 -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #141414 -highlightcolor black -relief flat 
    vTcl:DefineAlias "$top.but45" "acceptNewWindow" vTcl:WidgetProc "AddWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 10 -width 69 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent44 \
        -in $top -x 80 -y 10 -width 166 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 250 -y 10 -width 32 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

