#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jul 29, 2020 12:24:43 PM BST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ControlWindow_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = ControlWindow (root)
    ControlWindow_support.init(root, top)
    root.mainloop()

w = None
def create_ControlWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = ControlWindow (w)
    ControlWindow_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ControlWindow():
    global w
    w.destroy()
    w = None

class ControlWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1259x701+2978+273")
        top.minsize(1, 1)
        top.maxsize(2545, 1410)
        top.resizable(1, 1)
        top.title("Control")
        top.configure(background="#262626")
        top.configure(highlightbackground="#545454")
        top.configure(highlightcolor="black")

        self.addWindow = tk.Button(top)
        self.addWindow.place(relx=0.008, rely=0.014, height=32, width=32)
        self.addWindow.configure(activebackground="#004c0a")
        self.addWindow.configure(activeforeground="white")
        self.addWindow.configure(background="#141414")
        self.addWindow.configure(borderwidth="0")
        self.addWindow.configure(highlightbackground="#141414")
        self.addWindow.configure(relief="flat")

        self.windowList = tk.Listbox(top)
        self.windowList.place(relx=0.008, rely=0.071, relheight=0.223
                , relwidth=0.091)
        self.windowList.configure(background="#141414")
        self.windowList.configure(borderwidth="0")
        self.windowList.configure(font="TkFixedFont")
        self.windowList.configure(foreground="#dddddd")
        self.windowList.configure(highlightbackground="#141414")
        self.windowList.configure(selectbackground="#c4c4c4")

        self.prototypeCanvas = tk.Canvas(top)
        self.prototypeCanvas.place(relx=0.191, rely=0.014, relheight=0.971
                , relwidth=0.803)
        self.prototypeCanvas.configure(background="#000000")
        self.prototypeCanvas.configure(borderwidth="2")
        self.prototypeCanvas.configure(highlightbackground="#000000")
        self.prototypeCanvas.configure(highlightthickness="0")
        self.prototypeCanvas.configure(selectbackground="#000000")
        self.prototypeCanvas.configure(selectborderwidth="0")

if __name__ == '__main__':
    vp_start_gui()





