#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jul 29, 2020 12:55:53 PM BST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #262626 -highlightbackground #545454 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1259x701+2855+264
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Control"
    vTcl:DefineAlias "$top" "ControlWindow" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground #004c0a -activeforeground black -background #141414 \
        -borderwidth 0 -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #141414 -highlightcolor black -relief flat 
    vTcl:DefineAlias "$top.but43" "addWindow" vTcl:WidgetProc "ControlWindow" 1
    listbox $top.lis44 \
        -background #141414 -borderwidth 0 -font TkFixedFont \
        -foreground #dddddd -height 156 -highlightbackground #141414 \
        -highlightcolor black -selectbackground #c4c4c4 \
        -selectforeground black -width 114 
    .top42.lis44 configure -font "TkFixedFont"
    .top42.lis44 insert end text
    vTcl:DefineAlias "$top.lis44" "windowList" vTcl:WidgetProc "ControlWindow" 1
    canvas $top.can43 \
        -background #000000 -borderwidth 2 -closeenough 1.0 -height 681 \
        -highlightbackground #000000 -highlightcolor black \
        -highlightthickness 0 -insertbackground black \
        -selectbackground #000000 -selectborderwidth 0 \
        -selectforeground black -width 1011 
    vTcl:DefineAlias "$top.can43" "prototypeCanvas" vTcl:WidgetProc "ControlWindow" 1
    vTcl:copy_lock $top.can43
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 10 -y 10 -width 32 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lis44 \
        -in $top -x 10 -y 50 -width 114 -relwidth 0 -height 156 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can43 \
        -in $top -x 240 -y 10 -width 1011 -relwidth 0 -height 681 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

