#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jul 26, 2020 01:04:42 AM BST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ControlWindow_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = ControlWindow (root)
    ControlWindow_support.init(root, top)
    root.mainloop()

w = None
def create_ControlWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = ControlWindow (w)
    ControlWindow_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ControlWindow():
    global w
    w.destroy()
    w = None

class ControlWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+1007+237")
        top.minsize(1, 1)
        top.maxsize(2545, 1410)
        top.resizable(1, 1)
        top.title("Control")
        top.configure(background="#262626")
        top.configure(highlightbackground="#545454")
        top.configure(highlightcolor="black")

        self.addWindow = tk.Button(top)
        self.addWindow.place(relx=0.017, rely=0.022, height=32, width=32)
        self.addWindow.configure(activebackground="#004c0a")
        self.addWindow.configure(activeforeground="white")
        self.addWindow.configure(background="#141414")
        self.addWindow.configure(borderwidth="0")
        self.addWindow.configure(highlightbackground="#141414")
        self.addWindow.configure(relief="flat")

        self.windowList = tk.Listbox(top)
        self.windowList.place(relx=0.017, rely=0.111, relheight=0.347
                , relwidth=0.19)
        self.windowList.configure(background="#141414")
        self.windowList.configure(borderwidth="0")
        self.windowList.configure(font="TkFixedFont")
        self.windowList.configure(foreground="#b7b7b7")
        self.windowList.configure(highlightbackground="#141414")
        self.windowList.configure(selectbackground="#c4c4c4")

if __name__ == '__main__':
    vp_start_gui()





